### ISSUE TITLE
can't scroll down to select any option past the screen

### ISSUE THREAD

**Issue by tushortz** [globophobe/django-semantic-admin#88]
Thanks for your effort and hardwork. 

I noticed an issue in the Django admin.

I have a record admin that filters by country using `list_filter = ["country"]` with country being a foreign key relationship to Record model

Because I have about 100+ countries in my database, when I try to filter by a country (say Sao Tome), im unable to scroll down or search it if the options my screen is able to show is up to Maldives.

See example screenshots

**Screenshot 1**
<img width="1256" alt="image" src="https://github.com/globophobe/django-semantic-admin/assets/13158672/0c27972e-50f2-48ba-b162-dd255b560b54">

As you can see in screenshot 1 above, the country list is up to Bahamas on my screen but i want to select Sao Tome.

**Screenshot 2**

<img width="1286" alt="image" src="https://github.com/globophobe/django-semantic-admin/assets/13158672/ede845f1-8244-4700-90db-5dfa0e0ba2c4">

I can scroll using my mouse on the remaining options 

The issue here is that I am unable to scroll down to Sao Tome because the admin is only showing options until Maldives. not sure if its automatically puting a limit on how many select options are visible

**Comment by globophobe** [comment]
Admittedly, I added support for list_filter for completeness. And, have never used it on any sites except the semantic-admin demo. semantic-admin has optional integration with django_filter https://github.com/globophobe/django-semantic-admin?tab=readme-ov-file#awesome-optional-features

Personally, I always use django_filter

With list_filter, I think the behaviour of rendering a link, rather than a select element, is equivalent to the behaviour of the default django admin. 

Out of curiousity, is list_filter with 100+ options particularly usable with the default django admin? 

Do you absolutely need to use list_filter, or perhaps you can try using django_filter instead?

**Comment by tushortz** [comment]
For the Django admin, the filters are on the right hand side and it shows
all

**Comment by globophobe** [comment]
> For the Django admin, the filters are on the right hand side and it shows all

With 100+ options is that particularly usable, though. Using a `filterset_class` multiple options can be selected at the same time, and the options are searchable...

![filterclass](https://github.com/globophobe/django-semantic-admin/assets/891192/7b9749cd-ac72-4695-ab80-ca9c2221cf6b)

> Because I have about 100+ countries in my database, when I try to filter by a country (say Sao Tome), im unable to scroll down or search it if the options my screen is able to show is up to Maldives.

Anyway, adding `scrolling` to the css below seems to resolve the issue. I will add it to the next release

https://github.com/globophobe/django-semantic-admin/blob/0029612222d442bd335fda8516f8624c5cc9c0ec/semantic_admin/templates/admin/filter.html#L5

![scrolling](https://github.com/globophobe/django-semantic-admin/assets/891192/6e83f2d7-7f5a-402b-87c1-40545e48b25c)
